site_name: 'UMD DCB and Opt. Mezz.'
site_url: http://derek-colby.github.io/dcb_function

repo_name: derek-colby/dcb_function
repo_url: http://https://github.com/Derek-Colby/DCB_function

theme:
    name: 'cinder'
    logo: umd_logo.png
    include_search_page: false
    feature:
        tabs: true

nav:
    - Background: history/history.md
    - DCB:
        - DCB Function: dcb/dcb_func/dcb_func.md
        - Glossary: dcb/dcb_func/gloss.md
    - LVR:
        - LVR Function: lvr/lvr.md


markdown_extensions:
    - admonition
    - pymdownx.critic
    - pymdownx.caret
    - def_list
